# this file is for CICD using github actions
name: CI/CD for Dockerized Flask App

on:
    push:
        branches: [main]
    pull_request:     
        branches: [main]

jobs:
    buildTest: #for unit testing
        runs-on: ubuntu-latest #container
        
        steps:
        -   name: checking code from repository
            uses: actions/checkout@v3
        
        -   name: set up python #it sets up python version inside the container
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
        -   name: Run tests
            run: |
                pytest
            # pytest considers the unit tests in test file (here test_app.py)  
            
    #for publishing in docker hub        
    buildPublish:
        needs : buildTest #this will make buildTest runs first
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setting Docker Buildx
          uses: docker/setup-buildx-actions@v2.321.0 #provided by gitHub actions

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: build and push Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: /DockerFile
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/flasktest-app:latest

        - name: Image digest #it shows the buildsteps
          run: echo ${{steps.build-and-publish.outputs.digest}}    
           











